Algoritmo "FazSomaProcedimento"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/11/2022
Var
// Seção de Declarações das variáveis 
X, Y: Inteiro
Procedimento Soma(A, B: Inteiro)
Inicio
EscrevaL("Recebi o valor ", A)
EscrevaL("Recebi o valor ", B)
EscrevaL("A soma entre os dois é ", A+B)
FimProcedimento
Inicio
X <- 5
Y <- 3
Soma(X, Y)


Fimalgoritmo